---
title: "Higher Education Pathway for SPM Leavers"
author: "Naqiuddin"
date: "6/19/2020"
output: html_document
---


## What's Next After SPM? 

#### Congratulations on completing your SPM!!! 

Now that it's time to continue your education journey, it is really important that you make the right choice on which tertiary education to enrol in. If you are interested in pursuing a higher education in local universities but still unsure on which one or how to do so, worry not as this is a great platform to guide you throughout the process.

## About this application
<h4><i class="fa fa-list-alt"></i><b>List of Universities</b></h4>
Visit our University Finder to find the list of Universities available for your desired course.

<h4><i class="fa fa-table"></i><b>World Ranking</b></h4>
The ranking of universities can also play a big part in making your decision, therefore if you wish to seek for it, we have it covered in the World Ranking.

<h4><i class="fa fa-bar-chart"></i><b>Plot</b></h4>
We have plotted the univerty ranking for a better visualization.


<h4><i class="fa fa-sitemap"></i><b>Flow Chart</b></h4>
Not sure where to start? Feel free to refer to our flow chart and all the confusion will be answered. 



